name: CI

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - '**.sublime-syntax'
      - '**/syntax_test_*'
      - '**.tmPreferences'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'

jobs:
  syntax_tests:

    name: Syntax Tests (${{ matrix.build }})
    runs-on: ubuntu-latest
    permissions:
      # Passing one of default ones.
      contents: read
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - build: 'latest'
            # packages: master
          - build: stable
            # packages: binary

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          # default_packages: ${{ matrix.packages }}
